# Generated by Django 3.0.2 on 2020-02-10 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0003_sliderimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='indeximg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.FileField(upload_to='pics')),
                ('text', models.CharField(max_length=5)),
                ('head', models.TextField()),
                ('para', models.TextField()),
            ],
        ),
    ]
