# Generated by Django 3.0.2 on 2020-02-10 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0004_indeximg'),
    ]

    operations = [
        migrations.CreateModel(
            name='index2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='pics')),
                ('text1', models.CharField(max_length=5)),
                ('head1', models.TextField()),
                ('para1', models.TextField()),
                ('img2', models.FileField(upload_to='pics')),
                ('text2', models.CharField(max_length=5)),
                ('head2', models.TextField()),
                ('para2', models.TextField()),
                ('img3', models.FileField(upload_to='pics')),
                ('text3', models.CharField(max_length=5)),
                ('head3', models.TextField()),
                ('para3', models.TextField()),
            ],
        ),
    ]
