# Generated by Django 3.0.2 on 2020-02-10 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0005_index2'),
    ]

    operations = [
        migrations.CreateModel(
            name='index3',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('head', models.TextField()),
                ('para', models.TextField()),
            ],
        ),
    ]
