# Generated by Django 3.0.2 on 2020-02-11 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0006_index3'),
    ]

    operations = [
        migrations.CreateModel(
            name='trainingimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgfirst', models.FileField(upload_to='pics')),
                ('textfirst', models.CharField(max_length=5)),
                ('imgsec', models.FileField(upload_to='pics')),
                ('textsec', models.CharField(max_length=5)),
                ('imgthird', models.FileField(upload_to='pics')),
                ('textthird', models.CharField(max_length=5)),
                ('imgfour', models.FileField(upload_to='pics')),
                ('textfour', models.CharField(max_length=5)),
            ],
        ),
    ]
