# Generated by Django 3.0.2 on 2020-02-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0008_trainingtext'),
    ]

    operations = [
        migrations.CreateModel(
            name='galleryimg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(upload_to='')),
                ('img2', models.FileField(upload_to='')),
                ('img3', models.FileField(upload_to='')),
                ('img4', models.FileField(upload_to='')),
                ('img5', models.FileField(upload_to='')),
                ('img6', models.FileField(upload_to='')),
                ('img7', models.FileField(upload_to='')),
                ('img8', models.FileField(upload_to='')),
                ('img9', models.FileField(upload_to='')),
                ('img10', models.FileField(upload_to='')),
                ('img11', models.FileField(upload_to='')),
                ('img12', models.FileField(upload_to='')),
                ('img13', models.FileField(upload_to='')),
                ('img14', models.FileField(upload_to='')),
                ('img15', models.FileField(upload_to='')),
                ('img16', models.FileField(upload_to='')),
            ],
        ),
    ]
