# Generated by Django 3.0.2 on 2020-02-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('server', '0009_galleryimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
            ],
        ),
    ]
